# Generated by Django 3.2 on 2022-12-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0002_auto_20221209_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='block_date',
            new_name='block_data',
        ),
        migrations.RemoveField(
            model_name='input',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='plc',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='deleted_at',
        ),
    ]
