# Generated by Django 3.2 on 2022-12-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0004_auto_20221209_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='ad_start',
            new_name='Address_start_bit',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='address_bit',
            new_name='Address_start_byte',
        ),
    ]
