# Generated by Django 3.2 on 2022-12-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0006_auto_20221218_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='block_data',
            new_name='Data_Input',
        ),
    ]
