# Generated by Django 3.2 on 2022-12-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0007_rename_block_data_input_data_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='Data_Input',
            new_name='data_Input',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='Address_start_bit',
            new_name='address_start_bit',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='Address_start_byte',
            new_name='address_start_byte',
        ),
    ]
