# Generated by Django 3.2 on 2022-12-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0008_auto_20221218_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='data_Input',
            new_name='data_input',
        ),
    ]
