# Generated by Django 3.2 on 2022-12-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0009_rename_data_input_input_data_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('int', 'int'), ('bool', 'bool'), ('float', 'float')], max_length=5),
        ),
    ]
