# Generated by Django 3.2 on 2022-12-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_v4', models.GenericIPAddressField()),
                ('rack', models.IntegerField(verbose_name='rack')),
                ('slot', models.IntegerField(verbose_name='slot')),
            ],
        ),
    ]
