# Generated by Django 3.2 on 2022-12-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plc',
            name='ip_v4',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
